name: Run every 3 Hr 10 Min

on:
  schedule:
    - cron: "*/190 * * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      hanime_email: ${{ secrets.EID }}
      hanime_password: ${{ secrets.PASS }}
      webhook_url: ${{ secrets.HOOK }}

    steps:
      - name: Checkout the code nya~
        uses: actions/checkout@v2

      - name: Set up Python environment uwu~
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
          name: Set up Python environment

      - name: Install Python dependencies nyaa~
        run: pip install -r requirements.txt

      - name: Run getcoins.py uwu~
        run: python getcoins.py
        continue-on-error: true

      - name: Wait for 10 Seconds owo~
        run: sleep 10

      - name: Run webhook.py uwu~
        run: python webhook.py
        continue-on-error: true
